"""Fictional internal catalog for the PartTwin hackathon demo. Not real products."""

PARTS = [
    {
        "part_number": "BX-310",
        "name": "Compact Digital I/O Expansion Module",
        "status": "discontinued",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 110,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 16,
        "io_type": "PNP",
        "region": "Global",
        "unit_cost": 185.0,
        "availability": "Obsolete — do not reorder",
        "description": "Legacy 16-channel 24V DC digital I/O expansion for Compact I/O backplanes. M12-A 5-pin field connector. Discontinued after FY2023.",
        "missing_fields": [],
        "notes": "Master record for replacement investigations. Form factor 110x45x70 mm.",
    },
    {
        "part_number": "BX-421",
        "name": "Compact Digital I/O Expansion Module Mk2",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 118,
        "width_mm": 48,
        "height_mm": 72,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 16,
        "io_type": "PNP",
        "region": "Global",
        "unit_cost": 210.0,
        "availability": "Stock — 12 days",
        "description": "Current Compact I/O 16-channel digital expander. Same 24V DC M12-A 5-pin interface as BX-310. Housing is slightly larger than the discontinued unit.",
        "missing_fields": [],
        "notes": "Intended successor envelope. Envelope growth requires physical fit check on crowded rails.",
    },
    {
        "part_number": "BX-512",
        "name": "Compact Digital I/O Expansion Module (Terminal)",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "Screw terminal 8-pole",
        "length_mm": 112,
        "width_mm": 46,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP20",
        "channels": 16,
        "io_type": "PNP",
        "region": "Global",
        "unit_cost": 165.0,
        "availability": "Stock — 5 days",
        "description": "16-channel 24V digital I/O expansion for Compact I/O. Uses screw terminals instead of the M12 field connector. Cabinet-rated IP20.",
        "missing_fields": [],
        "notes": "Electrically similar function; field connector is not interchangeable with BX-310 harnesses.",
    },
    {
        "part_number": "BX-620",
        "name": "Compact Digital I/O Expansion Module 48V",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "48V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 110,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 16,
        "io_type": "PNP",
        "region": "Global",
        "unit_cost": 240.0,
        "availability": "Stock — 18 days",
        "description": "48V DC Compact I/O digital expander with M12-A 5-pin connector. Same envelope as BX-310 but different backplane voltage class.",
        "missing_fields": [],
        "notes": "Do not drop onto 24V Compact I/O backplanes.",
    },
    {
        "part_number": "BX-715",
        "name": "Compact Digital I/O Expansion Module (Archive)",
        "status": "limited_data",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": None,
        "connector": None,
        "length_mm": 110,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": None,
        "channels": 16,
        "io_type": "PNP",
        "region": "EMEA (unconfirmed)",
        "unit_cost": None,
        "availability": "Unknown — plant transfer",
        "description": "Incomplete Compact I/O digital expander record recovered after plant transfer. Channel count matches BX-310. Voltage class and field connector were not migrated.",
        "missing_fields": ["voltage", "connector", "ip_rating", "unit_cost"],
        "notes": "Treat as unknown until a datasheet or receiving inspection is attached.",
    },
    {
        "part_number": "BX-330",
        "name": "Compact Digital I/O Expansion 12V",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "12V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 110,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 16,
        "io_type": "PNP",
        "region": "Americas",
        "unit_cost": 190.0,
        "availability": "Stock — 9 days",
        "description": "12V DC variant of the Compact digital I/O expander.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "BX-418",
        "name": "Compact Analog I/O Expansion Module",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "analog_io_expansion",
        "function_label": "Analog I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 110,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 8,
        "io_type": "0-10V / 4-20mA",
        "region": "Global",
        "unit_cost": 265.0,
        "availability": "Stock — 7 days",
        "description": "Analog expansion for Compact I/O. Same housing language as digital units; different function.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "BX-440",
        "name": "Compact Digital I/O Expansion M12-D",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "M12-D 4-pin",
        "length_mm": 110,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 16,
        "io_type": "PNP",
        "region": "Global",
        "unit_cost": 198.0,
        "availability": "Stock — 14 days",
        "description": "24V digital I/O expander using Ethernet-coded M12-D instead of A-coded power/IO connector.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "BX-280",
        "name": "Compact Digital I/O 8-Channel",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 80,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 8,
        "io_type": "PNP",
        "region": "Global",
        "unit_cost": 140.0,
        "availability": "Stock — 4 days",
        "description": "Half-density 8-channel 24V digital expander. Same connector class, fewer channels, shorter body.",
        "missing_fields": [],
        "notes": "Channel count is a capacity risk versus BX-310.",
    },
    {
        "part_number": "BX-500",
        "name": "Compact Digital I/O 110V AC",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "110V AC",
        "connector": "M12-A 5-pin",
        "length_mm": 120,
        "width_mm": 50,
        "height_mm": 75,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP65",
        "channels": 16,
        "io_type": "Relay",
        "region": "Americas",
        "unit_cost": 255.0,
        "availability": "Stock — 21 days",
        "description": "AC-powered Compact digital module. Not for 24V DC backplanes.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "BX-905",
        "name": "Compact Digital I/O NPN Variant",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 110,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 16,
        "io_type": "NPN",
        "region": "APAC",
        "unit_cost": 188.0,
        "availability": "Stock — 11 days",
        "description": "NPN sinking outputs. Same mechanical and voltage class as BX-310; polarity differs.",
        "missing_fields": [],
        "notes": "Soft electrical preference: PNP vs NPN.",
    },
    {
        "part_number": "PS-210",
        "name": "24V DIN Rail Power Supply 5A",
        "status": "active",
        "family": "Power",
        "function_code": "power_supply",
        "function_label": "DIN Rail Power Supply",
        "voltage": "24V DC",
        "connector": "Screw terminal 4-pole",
        "length_mm": 125,
        "width_mm": 40,
        "height_mm": 125,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP20",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 92.0,
        "availability": "Stock — 3 days",
        "description": "Regulated 24V DC 5A supply for control cabinets.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "PS-310",
        "name": "24V DIN Rail Power Supply 10A",
        "status": "active",
        "family": "Power",
        "function_code": "power_supply",
        "function_label": "DIN Rail Power Supply",
        "voltage": "24V DC",
        "connector": "Screw terminal 4-pole",
        "length_mm": 140,
        "width_mm": 50,
        "height_mm": 125,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP20",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 128.0,
        "availability": "Stock — 6 days",
        "description": "Higher-capacity 24V cabinet power supply.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "PS-048",
        "name": "48V DIN Rail Power Supply 5A",
        "status": "active",
        "family": "Power",
        "function_code": "power_supply",
        "function_label": "DIN Rail Power Supply",
        "voltage": "48V DC",
        "connector": "Screw terminal 4-pole",
        "length_mm": 125,
        "width_mm": 40,
        "height_mm": 125,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP20",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 140.0,
        "availability": "Stock — 8 days",
        "description": "48V DC cabinet supply.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "MD-110",
        "name": "Servo Drive 1.5 kW 24V Logic",
        "status": "active",
        "family": "Motion",
        "function_code": "servo_drive",
        "function_label": "Servo Drive",
        "voltage": "24V DC",
        "connector": "M23 17-pin",
        "length_mm": 220,
        "width_mm": 70,
        "height_mm": 180,
        "mounting": "Panel",
        "ip_rating": "IP20",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 890.0,
        "availability": "Stock — 20 days",
        "description": "Compact servo drive with 24V logic supply.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "MD-220",
        "name": "Servo Drive 2.2 kW 48V Logic",
        "status": "active",
        "family": "Motion",
        "function_code": "servo_drive",
        "function_label": "Servo Drive",
        "voltage": "48V DC",
        "connector": "M23 17-pin",
        "length_mm": 240,
        "width_mm": 70,
        "height_mm": 180,
        "mounting": "Panel",
        "ip_rating": "IP20",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 1040.0,
        "availability": "Stock — 25 days",
        "description": "Higher power servo drive, 48V logic class.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "SN-12P",
        "name": "Inductive Proximity Sensor M12 PNP",
        "status": "active",
        "family": "Sensors",
        "function_code": "proximity_sensor",
        "function_label": "Inductive Proximity Sensor",
        "voltage": "24V DC",
        "connector": "M12-A 4-pin",
        "length_mm": 50,
        "width_mm": 12,
        "height_mm": 12,
        "mounting": "M12 threaded",
        "ip_rating": "IP67",
        "channels": 1,
        "io_type": "PNP",
        "region": "Global",
        "unit_cost": 28.0,
        "availability": "Stock — 2 days",
        "description": "M12 inductive prox, PNP NO, 24V DC.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "SN-18N",
        "name": "Inductive Proximity Sensor M18 NPN",
        "status": "active",
        "family": "Sensors",
        "function_code": "proximity_sensor",
        "function_label": "Inductive Proximity Sensor",
        "voltage": "24V DC",
        "connector": "M12-A 4-pin",
        "length_mm": 60,
        "width_mm": 18,
        "height_mm": 18,
        "mounting": "M18 threaded",
        "ip_rating": "IP67",
        "channels": 1,
        "io_type": "NPN",
        "region": "Global",
        "unit_cost": 32.0,
        "availability": "Stock — 2 days",
        "description": "M18 inductive prox, NPN NO.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "SN-30P",
        "name": "Inductive Proximity Sensor M30 PNP",
        "status": "active",
        "family": "Sensors",
        "function_code": "proximity_sensor",
        "function_label": "Inductive Proximity Sensor",
        "voltage": "24V DC",
        "connector": "M12-A 4-pin",
        "length_mm": 70,
        "width_mm": 30,
        "height_mm": 30,
        "mounting": "M30 threaded",
        "ip_rating": "IP67",
        "channels": 1,
        "io_type": "PNP",
        "region": "Global",
        "unit_cost": 41.0,
        "availability": "Stock — 4 days",
        "description": "Long-range M30 inductive prox.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "VL-24A",
        "name": "Solenoid Valve 24V DIN 43650",
        "status": "active",
        "family": "Fluid",
        "function_code": "solenoid_valve",
        "function_label": "Pneumatic Solenoid Valve",
        "voltage": "24V DC",
        "connector": "DIN 43650 Form A",
        "length_mm": 90,
        "width_mm": 32,
        "height_mm": 40,
        "mounting": "Namur / subplate",
        "ip_rating": "IP65",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 76.0,
        "availability": "Stock — 5 days",
        "description": "5/2 pneumatic valve, 24V coil, Form A connector.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "VL-24B",
        "name": "Solenoid Valve 24V DIN 43650 Form B",
        "status": "active",
        "family": "Fluid",
        "function_code": "solenoid_valve",
        "function_label": "Pneumatic Solenoid Valve",
        "voltage": "24V DC",
        "connector": "DIN 43650 Form B",
        "length_mm": 90,
        "width_mm": 32,
        "height_mm": 40,
        "mounting": "Namur / subplate",
        "ip_rating": "IP65",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 74.0,
        "availability": "Stock — 5 days",
        "description": "Same valve body as VL-24A with Form B coil connector.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "VL-110",
        "name": "Solenoid Valve 110V AC",
        "status": "active",
        "family": "Fluid",
        "function_code": "solenoid_valve",
        "function_label": "Pneumatic Solenoid Valve",
        "voltage": "110V AC",
        "connector": "DIN 43650 Form A",
        "length_mm": 90,
        "width_mm": 32,
        "height_mm": 40,
        "mounting": "Namur / subplate",
        "ip_rating": "IP65",
        "channels": None,
        "io_type": None,
        "region": "Americas",
        "unit_cost": 79.0,
        "availability": "Stock — 10 days",
        "description": "110V AC coil variant.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "HX-10",
        "name": "HMI 7-inch 24V",
        "status": "active",
        "family": "HMI",
        "function_code": "operator_hmi",
        "function_label": "Operator HMI Panel",
        "voltage": "24V DC",
        "connector": "Terminal block + RJ45",
        "length_mm": 200,
        "width_mm": 146,
        "height_mm": 42,
        "mounting": "Panel cutout",
        "ip_rating": "IP65 front",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 410.0,
        "availability": "Stock — 12 days",
        "description": "7-inch operator panel, 24V DC.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "HX-10L",
        "name": "HMI 7-inch 24V (legacy bezel)",
        "status": "discontinued",
        "family": "HMI",
        "function_code": "operator_hmi",
        "function_label": "Operator HMI Panel",
        "voltage": "24V DC",
        "connector": "Terminal block + RJ45",
        "length_mm": 200,
        "width_mm": 146,
        "height_mm": 38,
        "mounting": "Panel cutout",
        "ip_rating": "IP65 front",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 380.0,
        "availability": "Obsolete",
        "description": "Previous-generation 7-inch HMI. Thinner bezel than HX-10.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "CB-M12-5",
        "name": "M12-A 5-pin Cordset 5m",
        "status": "active",
        "family": "Cabling",
        "function_code": "cordset",
        "function_label": "Sensor/Actuator Cordset",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 5000,
        "width_mm": 12,
        "height_mm": 12,
        "mounting": "Inline",
        "ip_rating": "IP67",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 22.0,
        "availability": "Stock — 1 day",
        "description": "Straight M12-A 5-pin female cordset used on Compact I/O field ports.",
        "missing_fields": [],
        "notes": "Compatible accessory, not a module replacement.",
    },
    {
        "part_number": "CB-M8-4",
        "name": "M8 4-pin Cordset 5m",
        "status": "active",
        "family": "Cabling",
        "function_code": "cordset",
        "function_label": "Sensor/Actuator Cordset",
        "voltage": "24V DC",
        "connector": "M8 4-pin",
        "length_mm": 5000,
        "width_mm": 8,
        "height_mm": 8,
        "mounting": "Inline",
        "ip_rating": "IP67",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 18.0,
        "availability": "Stock — 1 day",
        "description": "M8 4-pin cordset. Not for BX-310 field ports.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "BX-199",
        "name": "Compact Safety I/O Module",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "safety_io",
        "function_label": "Safety I/O Module",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 130,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 8,
        "io_type": "PNP safety",
        "region": "Global",
        "unit_cost": 520.0,
        "availability": "Stock — 16 days",
        "description": "Safety-rated I/O. Same family look, different function and certification class.",
        "missing_fields": [],
        "notes": "Not a functional replacement for standard digital expansion.",
    },
    {
        "part_number": "BX-350",
        "name": "Compact Digital I/O (relay outputs)",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 125,
        "width_mm": 52,
        "height_mm": 78,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP65",
        "channels": 16,
        "io_type": "Relay",
        "region": "Global",
        "unit_cost": 230.0,
        "availability": "Stock — 13 days",
        "description": "Relay-output digital expander. Larger envelope than transistor PNP units.",
        "missing_fields": [],
        "notes": "Function class matches; output type and size are preferences/risks.",
    },
    {
        "part_number": "BX-610",
        "name": "Compact Communication Adapter EtherNet/IP",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "network_adapter",
        "function_label": "Network Adapter Module",
        "voltage": "24V DC",
        "connector": "M12-D 4-pin",
        "length_mm": 110,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 310.0,
        "availability": "Stock — 9 days",
        "description": "Network adapter for Compact I/O racks. Not a digital I/O expander.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "BX-311",
        "name": "Compact Digital I/O Expansion (last-time buy)",
        "status": "last_time_buy",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 110,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 16,
        "io_type": "PNP",
        "region": "Global",
        "unit_cost": 205.0,
        "availability": "Last-time buy — 4 units",
        "description": "Near-identical successor allotment of BX-310 remaining in surplus. Same envelope and interface.",
        "missing_fields": [],
        "notes": "Electrically and mechanically aligned; supply is not a long-term strategy.",
    },
    {
        "part_number": "RT-40",
        "name": "RTD Transmitter 24V",
        "status": "active",
        "family": "Process",
        "function_code": "temperature_transmitter",
        "function_label": "Temperature Transmitter",
        "voltage": "24V DC",
        "connector": "Screw terminal 4-pole",
        "length_mm": 98,
        "width_mm": 18,
        "height_mm": 90,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP20",
        "channels": 1,
        "io_type": "4-20mA",
        "region": "Global",
        "unit_cost": 64.0,
        "availability": "Stock — 3 days",
        "description": "Head/DIN RTD transmitter.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "RT-40H",
        "name": "RTD Transmitter 24V (head mount)",
        "status": "active",
        "family": "Process",
        "function_code": "temperature_transmitter",
        "function_label": "Temperature Transmitter",
        "voltage": "24V DC",
        "connector": "Screw terminal 4-pole",
        "length_mm": 45,
        "width_mm": 45,
        "height_mm": 28,
        "mounting": "DIN Form B head",
        "ip_rating": "IP00",
        "channels": 1,
        "io_type": "4-20mA",
        "region": "Global",
        "unit_cost": 58.0,
        "availability": "Stock — 3 days",
        "description": "Head-mount variant of RT-40.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "BX-800",
        "name": "Compact Digital I/O 32-Channel",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 160,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 32,
        "io_type": "PNP",
        "region": "Global",
        "unit_cost": 295.0,
        "availability": "Stock — 15 days",
        "description": "Double-density 32-channel expander. Same connector and voltage; much longer housing.",
        "missing_fields": [],
        "notes": "High dimensional risk on short rail segments.",
    },
    {
        "part_number": "BX-422",
        "name": "Compact Digital I/O Mk2 (NPN)",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 118,
        "width_mm": 48,
        "height_mm": 72,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 16,
        "io_type": "NPN",
        "region": "APAC",
        "unit_cost": 210.0,
        "availability": "Stock — 12 days",
        "description": "Mk2 housing with NPN outputs. Same dimensional growth as BX-421.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "FL-24",
        "name": "Fiber Optic Converter 24V",
        "status": "active",
        "family": "Network",
        "function_code": "media_converter",
        "function_label": "Fiber Media Converter",
        "voltage": "24V DC",
        "connector": "SC duplex + RJ45",
        "length_mm": 100,
        "width_mm": 25,
        "height_mm": 80,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP20",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 155.0,
        "availability": "Stock — 7 days",
        "description": "Industrial fiber converter.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "BX-010",
        "name": "Compact I/O End Cap",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "accessory",
        "function_label": "Rack Accessory",
        "voltage": None,
        "connector": None,
        "length_mm": 12,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 9.0,
        "availability": "Stock — 1 day",
        "description": "Protective end cap for Compact I/O assemblies.",
        "missing_fields": ["voltage", "connector"],
        "notes": "Accessory, not an I/O module.",
    },
    {
        "part_number": "GW-24",
        "name": "Modbus Gateway 24V",
        "status": "active",
        "family": "Network",
        "function_code": "protocol_gateway",
        "function_label": "Protocol Gateway",
        "voltage": "24V DC",
        "connector": "RJ45 + terminal",
        "length_mm": 110,
        "width_mm": 40,
        "height_mm": 90,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP20",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 275.0,
        "availability": "Stock — 8 days",
        "description": "Modbus TCP/RTU gateway.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "BX-721",
        "name": "Compact Digital I/O (draft revision)",
        "status": "limited_data",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": None,
        "width_mm": None,
        "height_mm": None,
        "mounting": None,
        "ip_rating": "IP67",
        "channels": 16,
        "io_type": "PNP",
        "region": "Unassigned",
        "unit_cost": 220.0,
        "availability": "Engineering sample",
        "description": "Draft Mk2-class digital expander. Electrical fields populated; mechanical envelope not released.",
        "missing_fields": ["length_mm", "width_mm", "height_mm", "mounting"],
        "notes": "Dimensional verification cannot be completed from catalog.",
    },
    {
        "part_number": "PS-210R",
        "name": "24V Redundant Power Supply 5A",
        "status": "active",
        "family": "Power",
        "function_code": "power_supply",
        "function_label": "DIN Rail Power Supply",
        "voltage": "24V DC",
        "connector": "Screw terminal 6-pole",
        "length_mm": 150,
        "width_mm": 55,
        "height_mm": 125,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP20",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 210.0,
        "availability": "Stock — 9 days",
        "description": "Redundant 24V supply with extra sense terminals.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "BX-390",
        "name": "Compact Digital I/O Conformal Coat",
        "status": "active",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 110,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 16,
        "io_type": "PNP",
        "region": "Global / harsh",
        "unit_cost": 245.0,
        "availability": "Stock — 19 days",
        "description": "Conformal-coated BX-310-class module. Same interface and envelope; coating for humidity.",
        "missing_fields": [],
        "notes": "Strong electrical/mechanical alignment; cost premium.",
    },
    {
        "part_number": "FN-1",
        "name": "Fan 24V 80mm",
        "status": "active",
        "family": "Thermal",
        "function_code": "cooling_fan",
        "function_label": "Cabinet Fan",
        "voltage": "24V DC",
        "connector": "Spade 2-pin",
        "length_mm": 80,
        "width_mm": 80,
        "height_mm": 25,
        "mounting": "Panel",
        "ip_rating": "IP20",
        "channels": None,
        "io_type": None,
        "region": "Global",
        "unit_cost": 16.0,
        "availability": "Stock — 1 day",
        "description": "Cabinet cooling fan.",
        "missing_fields": [],
        "notes": "",
    },
    {
        "part_number": "BX-555",
        "name": "Compact Digital I/O (conflicting spec)",
        "status": "limited_data",
        "family": "Compact I/O",
        "function_code": "digital_io_expansion",
        "function_label": "Digital I/O Expansion Module",
        "voltage": "24V DC",
        "connector": "M12-A 5-pin",
        "length_mm": 110,
        "width_mm": 45,
        "height_mm": 70,
        "mounting": "DIN rail 35mm",
        "ip_rating": "IP67",
        "channels": 16,
        "io_type": "PNP",
        "region": "Global",
        "unit_cost": 199.0,
        "availability": "Hold — spec conflict",
        "description": "Catalog lists 24V DC; a scanned note in the archive mentions 30V max without confirmation.",
        "missing_fields": [],
        "notes": "CONFLICT: catalog voltage 24V DC vs archive handwritten '30V max?'. Do not treat as verified match.",
        "spec_conflict": True,
    },
]

DATASHEETS = [
    {
        "part_number": "BX-310",
        "title": "DS-BX-310 Internal",
        "section": "§2 Electrical",
        "body": "Supply: 24V DC ±10% from Compact I/O backplane. Field connector: M12-A 5-pin female, A-coded. Outputs: 16-channel PNP, 0.5A per channel. Not rated for 48V backplanes.",
    },
    {
        "part_number": "BX-310",
        "title": "DS-BX-310 Internal",
        "section": "§4 Mechanical",
        "body": "Envelope 110 x 45 x 70 mm. DIN rail 35 mm. IP67 when M12 connectors are mated. Adjacent module clearance 2 mm.",
    },
    {
        "part_number": "BX-421",
        "title": "DS-BX-421 Internal",
        "section": "§1 Scope",
        "body": "Digital I/O expansion for Compact I/O 24V DC racks. Intended functional successor to discontinued BX-310. Interface: M12-A 5-pin A-coded. 16-channel PNP.",
    },
    {
        "part_number": "BX-421",
        "title": "DS-BX-421 Internal",
        "section": "§3 Mechanical",
        "body": "Envelope 118 x 48 x 72 mm (Mk2 housing). DIN rail 35 mm. Installer must confirm rail pitch and cabinet door clearance versus BX-310 110 x 45 x 70 mm. This document is an internal specification extract, not a certified interchangeability statement.",
    },
    {
        "part_number": "BX-512",
        "title": "DS-BX-512 Internal",
        "section": "§2 Connections",
        "body": "Field wiring is screw terminal 8-pole, IP20. Do not use with M12 harnesses designed for BX-310. Backplane: 24V DC Compact I/O.",
    },
    {
        "part_number": "BX-620",
        "title": "DS-BX-620 Internal",
        "section": "§2 Electrical",
        "body": "Supply class: 48V DC Compact I/O backplane only. Connector: M12-A 5-pin. Not compatible with 24V DC BX-310 systems. Applying 24V will not meet switching thresholds; applying 48V to a 24V rack is a hard mismatch.",
    },
    {
        "part_number": "BX-715",
        "title": "Archive stub BX-715",
        "section": "§0 Record quality",
        "body": "Plant-transfer stub. Channel count 16 PNP is listed. Voltage class and connector type were not migrated. No mechanical drawing attached. Treat all interface fields as unknown pending receiving inspection.",
    },
    {
        "part_number": "BX-418",
        "title": "DS-BX-418 Internal",
        "section": "§1 Function",
        "body": "Analog I/O expansion (0-10V / 4-20mA). Not a digital discrete expander. Housing family Compact I/O 24V M12-A 5-pin.",
    },
    {
        "part_number": "BX-311",
        "title": "DS-BX-311 Internal",
        "section": "§1",
        "body": "Last-time-buy allotment mechanically and electrically aligned with BX-310: 24V DC, M12-A 5-pin, 110 x 45 x 70 mm, 16ch PNP.",
    },
    {
        "part_number": "BX-390",
        "title": "DS-BX-390 Internal",
        "section": "§1",
        "body": "Conformal-coated Compact digital I/O. 24V DC, M12-A 5-pin, 110 x 45 x 70 mm, 16ch PNP. Coating does not change connector or voltage class.",
    },
    {
        "part_number": "BX-555",
        "title": "Scan note BX-555",
        "section": "Archive",
        "body": "Handwritten receiving note: '30V max?? confirm with vendor'. Catalog still lists 24V DC. Conflict unresolved.",
    },
]

HISTORICAL_VAULT_DECISIONS = [
    {
        "original_part": "BX-310",
        "recommended_part": "BX-421",
        "verdict": "APPROVED_POTENTIAL",
        "engineer_name": "Ada Engineer",
        "engineer_notes": "Historical precedent: Fit check scheduled on Line 3. Form factor verified against rail clearance.",
        "created_at": "2025-11-14T09:30:00+00:00",
        "snapshot": {
            "historical": True,
            "source": "Line 3 Pilot Qualification Precedent",
            "notes": "Historical engineering reference used as catalog evidence.",
        },
    },
]

